### rbac for developer restrict staging namespace ###
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-staging
  namespace: staging
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: staging
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["ingresses", "services", "pods/exec", "crontabs", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]  
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: staging
subjects:
- kind: ServiceAccount
  name: developer-staging
  namespace: staging
- kind: User
  name: abdi@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: bobby@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: ci-cd-109@zeus-cloud-315880311.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io
---
### rbac for read secret ###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-read-secret
  namespace: staging
subjects:
- kind: ServiceAccount
  name: developer-staging
  namespace: staging
- kind: User
  name: abdi@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
