# rbac for engineer restrict staging namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-engineer-secret-reader
  namespace: staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: staging-engineer-secret-reader-roles
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-engineer-secret-reader-rolebinding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: staging-engineer-secret-reader
  namespace: staging
- kind: User
  name: abdi@makan.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: staging-engineer-secret-reader-roles
  apiGroup: rbac.authorization.k8s.io  
