### rbac for developer restrict staging namespace ###
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-staging
  namespace: staging
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
  namespace: staging
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["ingresses", "services", "deployments", "pods", "pods/log", "crontabs", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/exec", "pods/portforward"]
  verbs: ["create"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules", "virtualservices", "gateway"]
  verbs: ["get", "list", "watch",]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-role
  namespace: staging
subjects:
- kind: ServiceAccount
  name: developer-staging
  namespace: staging
- kind: User
  name: abdi@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: bobby@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: ci-cd-109@zeus-cloud-315880311.iam.gserviceaccount.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
### rbac for read secret ###
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: secret-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: developer-read-secret
  namespace: staging
subjects:
- kind: ServiceAccount
  name: developer-staging
  namespace: staging
- kind: User
  name: abdi@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
