# rbac for engineer restrict staging namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: staging-engineer
  namespace: staging
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-engineer-roles
  namespace: staging
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/attach"]
  verbs: ["create"]  
- apiGroups: [""]
  resources: ["pods/portforward"]
  verbs: ["create"]
#- apiGroups: [""]
#  resources: ["pods/exec"]
#  verbs: ["create"]  
- apiGroups: ["extensions", "apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "patch"]  
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "watch", "patch"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]  
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["crontabs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["destinationrules", "virtualservices"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.istio.io"]
  resources: ["gateway"]
  verbs: ["get", "list", "watch"]  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: staging-engineer-rolebinding
  namespace: staging
subjects:
- kind: ServiceAccount
  name: staging-engineer
  namespace: staging
- kind: User
  name: abdi@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: agus@abdidarmawan.com
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: staging-engineer-roles
  apiGroup: rbac.authorization.k8s.io
